musicapp/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'users#new'
  # Defines the root path route ("/")
  # root "articles#index"
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :bands
end

musicapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

musicapp/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Band < ApplicationRecord
    validates :name, presence: true, uniqueness: true
end

musicapp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
    before_validation :ensure_session_token
    validates :email, :session_token, uniqueness: true, presence: true
    validates :password_digest, presence: true
    validates :password, length: {minimum: 6}, allow_nil: true
    attr_reader :password
    #spire
    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        if user && user.is_password?(password)
            user
        else
            nil
        end
    end

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
        @password = password
    end

    def is_password?(password)
        password_object = BCrypt::Password.new(self.password_digest)
        password_object.is_password?(password)
    end

    def ensure_session_token
        self.session_token ||= session_token = SecureRandom::urlsafe_base64
    end

    def reset_session_token!
        self.session_token = SecureRandom::urlsafe_base64
        self.save!
        self.session_token
    end
end

musicapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # skip_before_action :verify_authenticity_token
    helper_method :current_user, :logged_in?

    #CRLLL

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def login!(user)
        session[:session_token] = user.reset_session_token!
    end

    def logout!
        @current_user.reset_session_token! if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end

    def logged_in?
        !!current_user
    end

    def require_logged_in
        redirect_to new_session_url if !logged_in?
    end
end

musicapp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    before_action :set_band, only: [:show, :edit, :update, :destroy]
    before_action :require_logged_in

    def index
        @bands = Band.all
        render :index
    end

    def create
        @band = Band.new(band_params)
        if @band.save
            render :show
        else
            flash.now[:errors] = @band.errors.full_messages
            render :new
        end
    end

    def new
        @band = Band.new
        render :new
    end

    def edit
        render :edit
    end

    def show
        render :show
    end

    def update
        # debugger
        if @band.update(band_params)
            redirect_to band_url(@band.id)
        else
            flash.now[:errors] = @band.errors.full_messages
            render :edit
        end
    end

    def destroy
        @band.destroy
        render :index
    end

    def set_band
        @band = Band.find_by(id: params[:id])
    end

    private 

    def band_params
        params.require(:band).permit(:name)
    end
end

musicapp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :require_logged_in, only: [:destroy]
    def new
        # @user = User.new
        render :new 
    end

    def create
        user = User.find_by_credentials(params[:user][:email], params[:user][:password])
        if user
            login!(user)
            redirect_to bands_url
        else
            flash.now[:errors] = ['invalid username or password']
            render :new
        end
    end

    def destroy
        logout!
        # render :new
        redirect_to new_session_url
    end
end

musicapp/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user= User.new
        render :new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login!(@user)
            redirect_to bands_url
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def show
        @user = User.find_by(id: params[:id])
        render :show
    end

    private
    def user_params
        params.require(:user).permit(:email, :password)
    end
end

musicapp/app/helpers/application_helper.rb
module ApplicationHelper
end

musicapp/app/helpers/bands_helper.rb
module BandsHelper
end

musicapp/app/helpers/sessions_helper.rb
module SessionsHelper
end

musicapp/app/helpers/users_helper.rb
module UsersHelper
end

musicapp/app/views/bands/edit.html.erb
<h2>Edit Band</h2>

<form action = "<%= band_url(@band)%>" method = "post">
    <input type = "hidden" name = "_method" value = "PATCH">
    <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"
    >

    <label>Name:
    <input type ="string" name = "band[name]" value = "<%=@band.name %>">
    </label>

    <input type = "submit" value = "Submit">
</form>

musicapp/app/views/bands/index.html.erb
<h2>Bands</h2>

<%@bands.each do |band| %>
    <ul>
    <li><%= band.name %></li>
    <ul>
<% end %>

musicapp/app/views/bands/new.html.erb
<h2>New Band</h2>

<form action = '<%= bands_url%>' method = 'post'>
    <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"
    >

    <label>Name:
    <input type ="string" name = "band[name]" value = "">
    </label>

    <input type = "submit" value = "Submit">
</form>

musicapp/app/views/bands/show.html.erb
<h2><%= @band.name %></h2>

musicapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
      <%if logged_in?%>
    <p>Welcome <%= current_user.email%>!</p>
    <form action = "<%=session_url%>" method = "post">
      <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>"
      >
      <input  type = "hidden" name = "_method" value = "DELETE">
      <input type = "submit" value = "Log Out">
    <%else%>
      <a href="<%= new_session_url%>">Log In</a>
      <a href="<%= new_user_url%>">Sign Up</a>
    <% end %>
  </header>

  <h1> MUSIC APP</h1>
  <div class = "body">

  <% if flash[:errors] %>
  <ul>
    <% flash[:errors].each do |error| %>
    <li><%=error%></li>
    <% end %>
  </ul>
  <% end %>
    <%= yield %>
    </div>
  </body>
</html>

musicapp/app/views/users/new.html.erb
<h2>NEW USER</h2>


<form action="<%= new_session_url%>">
    <input type="submit" value="Go to Sign-in!" />
</form>


<br>
<form action = '<%= users_url%>' method = 'post'>
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"
  >
    <label>Username:
    <input type = "email" name = "user[email]" value = "">
    </label>  
    <br>
    <br>
    <label>Password:
    <input type = "password" name = "user[password]" value = "">
    </label>
    <br>
    <input type = "submit" value = "Submit">
</div>
</form>

musicapp/app/views/users/show.html.erb
<p>Logged in as: <%= @user.email %></p>